package io.github.ungle.kong.client.enums;

public enum InnerPluginName {
	BASIC_AUTH,
	HMAC_AUTH,
	JWT,
	KEY_AUTH,
	LDAP_AUTH,
	OAUTH2,
	SESSION,
	ACME,
	BOT_DETECTION,
	CORS,
	IP_RESTRICTION,
	ACL,
	PROXY_CACHE,
	RATE_LIMITING,
	REQUEST_SIZE_LIMITING,
	REQUEST_TERMINATION,
	RESPONSE_RATELIMITING,
	AWS_LAMBDA,
	AZURE_FUNCTIONS,
	OPENWHISK,
	PRE_FUNCTION,
	POST_FUNCTION,
	DATADOG,
	OPENTELEMETRY,
	PROMETHEUS,
	STATSD,
	ZIPKIN,
	CORRELATION_ID,
	GRPC_GATEWAY,
	GRPC_WEB,
	REQUEST_TRANSFORMER,
	RESPONSE_TRANSFORMER,
	FILE_LOG,
	HTTP_LOG,
	LOGGLY,
	SYSLOG,
	TCP_LOG,
	UDP_LOG;
	
	public String getPluginName() {
		return this.name().toLowerCase().replaceAll("_", "-");
	}

}
